config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'account', to: 'devise/registrations#edit'
  end

  resources :issues, only: [:index, :show] do
    resources :positions, only: :show do
      resources :links, only: [:new, :create, :destroy], controller: 'issues/positions/links'
    end
    resources :links, only: [:new, :create, :destroy], controller: 'issues/links'
  end

  get 'profile', to: 'profiles#show'

  namespace :profile do
    resources :issues, except: [:index, :destroy] do
      resources :positions, except: [:index, :destroy] do
        resources :supports, only: [:create, :destroy]
      end
    end
    resources :preferences, only: :update
  end

  root 'issues#index'
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :supports, dependent: :destroy
  has_many :adoptions, through: :supports
  has_many :supporting_profiles, through: :adoptions, source: :profile
  has_many :links, as: :linkable, dependent: :destroy

  scope :where_issue, lambda { |issue|
    joins(:adoptions).where(adoptions: {issue: issue}).distinct
  }

  validates :name, uniqueness: true, presence: true

  scope :published, -> { where published: true }
end

app/controllers/issues/positions/links_controller.rb
class Issues::Positions::LinksController < LinksController
  before_action :issue

  private

  def linkable
    @linkable ||= Position.find params[:position_id]
  end

  def path_success
    profile_issue_position_path(issue, linkable)
  end

  def issue
    @issue ||= Issue.find params[:issue_id]
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :check_published!

  def show
    @issue = Issue.find_by_id params[:issue_id]
    @links = @position.links
    return unless user_signed_in?

    @support = current_user.supports.where_issue(@issue).find_by position: @position
  end

  private

  def check_published!
    @position = Position.find_by_id params[:id]
    return if @position.published

    redirect_to issues_path, alert: 'Position not published'
  end
end

app/controllers/profile/positions_controller.rb
class Profile::PositionsController < ApplicationController
  before_action :authenticate_user!

  after_action :support_position, only: :create

  def show
    @issue = Issue.find_by_id params[:issue_id]
    @position = Position.find_by_id params[:id]
    @links = @position.links
  end

  def new
    @issue = Issue.find_by_id params[:issue_id]
    @position = Position.new
  end

  def edit
    @issue = Issue.find_by_id params[:issue_id]
    @position = Position.find_by_id params[:id]
  end

  def update
    @issue = Issue.find_by_id params[:issue_id]
    @position = Position.find_by_id params[:id]
    if @position.update(position_params)
      redirect_to profile_issue_position_path(@issue, @position),
        notice: 'Successfully Updated Position'
    else
      flash[:alert] = @position.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create
    @issue = Issue.find_by_id(params[:issue_id])
    @position = Position.new(position_params)
    if @position.save
      redirect_to profile_issue_path(@issue),
        notice: 'Successfully Created Position'
    else
      flash[:alert] = @position.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def position_params
    params.require(:position).permit(:name, :outline)
  end

  def support_position
    return unless flash[:notice].present?

    adoption = Adoption.find_or_create_by(
      profile: current_user.profile,
      issue: @issue
    )
    Support.create(
      position: @position,
      adoption: adoption,
      preference: (adoption.supports.count + 1)
    )
  end
end

app/views/positions/show.haml
- content_for :title, @position.name
%h1= yield :title
%p
  Position on Issue:
  %strong= @issue.name
%p
  Support:
  %strong
    - if @support.present?
      You Support this Position
    - else
      You do not Support this Position
- if @position.outline.present?
  = render 'layouts/article', text: @position.outline
- if user_signed_in? || @links.any?
  %p
    %strong Supporting Resources
  = render 'layouts/links', path_to_new: new_issue_position_link_path(@issue, @position), links: @links
%p
  %strong Actions
%hr
.tile-container
  - if @support.present?
    = link_to profile_issue_position_support_path(@issue, @position, @support), method: :delete, class: 'tile' do
      = 'Remove Support'
    = link_to edit_profile_issue_position_path(@issue, @position), class: 'tile' do
      = 'Edit Position'
  - elsif user_signed_in?
    = link_to profile_issue_position_supports_path(@issue, @position), method: :post, class: 'tile' do
      = 'Support Position'
  = link_to issue_path(@issue), class: 'tile' do
    = 'Back to Issue'
  = link_to issues_path, class: 'tile' do
    = 'All Issues'
  = render partial: 'layouts/authentication_tiles'