config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'account', to: 'devise/registrations#edit'
  end

  resources :issues, only: [:index, :show] do
    resources :positions, only: :show do
      resources :links, only: [:new, :create, :destroy], controller: 'issues/positions/links'
    end
    resources :links, only: [:new, :create, :destroy], controller: 'issues/links'
  end

  get 'profile', to: 'profiles#show'

  namespace :profile do
    resources :issues, except: [:index, :destroy] do
      resources :positions, except: [:index, :destroy] do
        resources :supports, only: [:create, :destroy]
      end
    end
    resources :preferences, only: :update
  end

  root 'issues#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :adoptions, dependent: :destroy
  has_many :supports, through: :adoptions
  has_many :positions, through: :supports
  has_many :submissisons
  has_many :groups, through: :submissions
  has_many :links, as: :linkable, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  scope :published, -> { where published: true }
end

app/controllers/issues/links_controller.rb
class Issues::LinksController < LinksController
  private

  def linkable
    @linkable ||= Issue.find params[:issue_id]
  end

  def path_success
    profile_issue_path(@linkable)
  end
end

app/controllers/issues/positions/links_controller.rb
class Issues::Positions::LinksController < LinksController
  before_action :issue

  private

  def linkable
    @linkable ||= Position.find params[:position_id]
  end

  def path_success
    profile_issue_position_path(issue, linkable)
  end

  def issue
    @issue ||= Issue.find params[:issue_id]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :check_published!, only: :show

  def index
    @issues = Issue.published.joins(:supports).uniq.take(12)
  end

  def show
    @positions = @issue.positions
    @links = @issue.links
    return unless user_signed_in?

    @adoption = current_user.adoptions.find_by issue: @issue
  end

  private

  def check_published!
    @issue = Issue.find params[:id]
    return if @issue.published

    redirect_to issues_path, alert: 'Issue not published'
  end
end

app/controllers/profile/issues_controller.rb
class Profile::IssuesController < ApplicationController
  before_action :authenticate_user!

  def show
    @issue = Issue.find_by_id params[:id]
    @supports = current_user.supports.where_issue(@issue)
      .order(:preference)
      .preload(:position)
    @links = @issue.links
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.find_or_initialize_by(issue_params)
    @adoption = Adoption.new(profile: current_user.profile, issue: @issue)
    handle_create
  end

  def edit
    @issue = Issue.find params[:id]
  end

  def update
    @issue = Issue.find params[:id]
    if @issue.update issue_params
      redirect_to profile_issue_path(@issue), notice: 'Issue successfully updated'
    else
      flash[:alert] = @issue.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :outline)
  end

  def handle_create
    if @issue.persisted? && @adoption.save
      redirect_to profile_issue_path(@issue),
        notice: 'New issue adopted'
    elsif @issue.save && @adoption.save
      redirect_to profile_issue_path(@issue),
        notice: 'New issue created'
    else
      handle_create_error
    end
  end

  def handle_create_error
    flash[:alert] = @issue.errors.full_messages.to_sentence +
                    @adoption.errors.full_messages.to_sentence
    render :new
  end
end

app/views/issues/index.haml
- content_for :title, 'Home'
%landing
  %logo Open Civic Platform
.container
  %p
    %strong Actions
  %hr
  .tile-container
    = render partial: 'layouts/authentication_tiles'

app/views/issues/show.haml
- content_for :title, @issue.name
%h1= yield :title
- if @issue.outline.present?
  = render 'layouts/article', text: @issue.outline
- if user_signed_in? || @links.any?
  %p
    %strong Background Resources
  = render 'layouts/links', path_to_new: new_issue_link_path(@issue), links: @links
%p
  %strong Positions
.tile-container
  - @positions.each do |position|
    = render 'layouts/tile', url: issue_position_path(@issue, position), title: position.name
  - if @adoption.present?
    = link_to new_profile_issue_position_path(@issue), class: 'tile' do
      = 'Add Position'
%p
  %strong Actions
%hr
.tile-container
  - if @adoption.present?
    = link_to profile_issue_path(@issue), class: 'tile' do
      = 'Preferences'
  - elsif user_signed_in?
    = link_to profile_issues_path(issue: {name: @issue.name}), method: :post, class: 'tile' do
      = 'Adopt Issue'
  = link_to issues_path, class: 'tile' do
    = 'All Issues'
  = render partial: 'layouts/authentication_tiles'