config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'account', to: 'devise/registrations#edit'
  end

  resources :issues, only: [:index, :show] do
    resources :positions, only: :show do
      resources :links, only: [:new, :create, :destroy], controller: 'issues/positions/links'
    end
    resources :links, only: [:new, :create, :destroy], controller: 'issues/links'
  end

  get 'profile', to: 'profiles#show'

  namespace :profile do
    resources :issues, except: [:index, :destroy] do
      resources :positions, except: [:index, :destroy] do
        resources :supports, only: [:create, :destroy]
      end
    end
    resources :preferences, only: :update
  end

  root 'issues#index'
end

app/views/layouts/_article.haml
%article
  - text.split(/\r\n\r\n/).each do |line|
    %p= line

app/views/layouts/_authentication_links.html.haml
%nav.navbar.sticky-top.navbar-light.bg-light
  = link_to 'Open Civic Platform', root_path, class: 'navbar-brand'
  .btn-group{role: "group"}
    %button#btnGroupDrop1.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
      Account
    .dropdown-menu{"aria-labelledby" => "btnGroupDrop1"}
      - if user_signed_in?
        = link_to 'Profile', profile_path, class: 'dropdown-item'
        = link_to 'Email/Password', account_path, class: 'dropdown-item'
        = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
      - else
        = link_to 'Sign In', sign_in_path, class: 'dropdown-item'
        = link_to 'Sign Up', sign_up_path, class: 'dropdown-item'

app/views/layouts/_authentication_tiles.haml
- if user_signed_in?
  = link_to profile_path, class: 'tile' do
    Profile
  = link_to destroy_user_session_path, method: :delete, class: 'tile' do
    Sign Out
- else
  = link_to sign_in_path, class: 'tile' do
    Sign In
  = link_to sign_up_path, class: 'tile' do
    Sign Up

app/views/layouts/_links.haml
.tile-container
  - links.each do |link|
    = render 'layouts/tile', url: link.url, title: link.title
  - if user_signed_in?
    = link_to path_to_new, class: 'tile' do
      = 'Add Link'

app/views/layouts/_tile.html.haml
= link_to url, class: 'tile' do
  = truncate title, length: 60

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title= "#{yield(:title)} | Open Civic Platform"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'application/favicon'
  %body
    .flashes
      - flash.each do |type, msg|
        - next if type == 'timedout'
        %p{class: type}= msg
    - if current_page?(root_path)
      = yield
    - else
      .container
        = render 'layouts/authentication_links'
        = yield
    %section.footer